name: Publish Docs

on:
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  publish:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup
        uses: ./.github/workflows/setup

      - name: Build webpage
        run: |
          npx hardhat coverage
          npx hardhat docs --coverage ./coverage

      - name: Upload webpage
        uses: actions/upload-pages-artifact@v1
        with:
          path: "./docs/www"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
